apiVersion: v1
kind: Service
metadata:
  name: {{ template "7dtd.fullname" . }}-server
  labels:
    app: {{ template "7dtd.name" . }}
    chart: {{ template "7dtd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: "{{ .Values.service.type }}"
  {{ with .Values.service.clusterIP }}clusterIP: {{ . | quote }}{{ end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    {{- range .Values.service.ports }}
    {{- if .enabled }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ template "7dtd.name" . }}
    release: {{ .Release.Name }}
