---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "7dtd.fullname" . }}
  labels:
    app: {{ template "7dtd.name" . }}
    chart: {{ template "7dtd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "7dtd.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "7dtd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "7dtd.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- tpl (.Values.env) $ | nindent 10 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 10 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 10 }}
          ports:
          - name: 7dtd-tcp
            containerPort: 26900
            protocol: TCP
          - name: 7dtd-udp
            containerPort: 26900
            protocol: UDP
          - name: 7dtd-udp2
            containerPort: 26901
            protocol: UDP
          - name: 7dtd-udp3
            containerPort: 26902
            protocol: UDP
          - name: 7dtd-webadmin
            containerPort: 8080
            protocol: TCP
          - name: 7dtd-telnet
            containerPort: 8081
            protocol: TCP
          - name: 7dtd-webserver
            containerPort: 8082
            protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}