---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "7dtd.fullname" . }}
  labels:
    app: {{ template "7dtd.name" . }}
    chart: {{ template "7dtd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "7dtd.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "7dtd.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "7dtd.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          command: ["sh", "-c", "echo 'nobody soft nofile 10240' | tee -a /etc/security/limits.conf; exec /home/sdtdserver/user.sh"]
          securityContext:
            privileged: true
          ports:
          - name: 7dtd-tcp
            containerPort: 26900
            protocol: TCP
          - name: 7dtd-udp
            containerPort: 26900
            protocol: UDP
          - name: 7dtd-udp2
            containerPort: 26901
            protocol: UDP
          - name: 7dtd-udp3
            containerPort: 26902
            protocol: UDP
          - name: 7dtd-webadmin
            containerPort: 8080
            protocol: TCP
          - name: 7dtd-telnet
            containerPort: 8081
            protocol: TCP
          - name: 7dtd-http
            containerPort: 8082
            protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.worldSaves.enabled }}
            - name: world-saves
              mountPath: {{ .Values.persistence.worldSaves.mountPath }}
            {{- end }}
            {{- if .Values.persistence.lgsmConfig.enabled }}
            - name: lgsm-config
              mountPath: {{ .Values.persistence.lgsmConfig.mountPath }}
            {{- end }}
            {{- if .Values.persistence.serverFiles.enabled }}
            - name: server-files
              mountPath: {{ .Values.persistence.serverFiles.mountPath }}
            {{- end }}
            {{- if .Values.persistence.logs.enabled }}
            - name: logs
              mountPath: {{ .Values.persistence.logs.mountPath }}
            {{- end }}
            {{- if .Values.persistence.backups.enabled }}
            - name: backups
              mountPath: {{ .Values.persistence.backups.mountPath }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.worldSaves.enabled }}
        - name: world-saves
          persistentVolumeClaim:
            claimName: {{ template "7dtd.fullname" . }}-world-saves
        {{- end }}
        {{- if .Values.persistence.lgsmConfig.enabled }}
        - name: lgsm-config
          persistentVolumeClaim:
            claimName: {{ template "7dtd.fullname" . }}-lgsm-config
        {{- end }}
        {{- if .Values.persistence.serverFiles.enabled }}
        - name: server-files
          persistentVolumeClaim:
            claimName: {{ template "7dtd.fullname" . }}-server-files
        {{- end }}
        {{- if .Values.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ template "7dtd.fullname" . }}-logs
        {{- end }}
        {{- if .Values.persistence.backups.enabled }}
        - name: backups
          persistentVolumeClaim:
            claimName: {{ template "7dtd.fullname" . }}-backups
        {{- end }}